#!/bin/sh
# Prepend tools/license_header.txt to every C source/header file
# under the given paths.  Idempotent: skip a file that already
# carries the marker string.
#
# Usage: ./tools/add_license.sh src regress tools

set -eu

HEADER=tools/license_header.txt
MARKER='Renaud Allard <renaud@allard.it>'

if [ ! -f "$HEADER" ]; then
	echo "missing $HEADER" >&2
	exit 1
fi

if [ $# -eq 0 ]; then
	set -- src regress tools
fi

for root in "$@"; do
	find "$root" -type f \( -name '*.c' -o -name '*.h' \) \
		-print | while read -r f; do
		case "$f" in
		src/include/config.h) continue ;;   # generated by configure
		src/greeter/font.c)   ;;            # font data; keep generated
		esac
		if grep -q -F "$MARKER" "$f"; then
			continue
		fi
		tmp=$(mktemp "tmp/.licadd.XXXXXX")
		cat "$HEADER" "$f" > "$tmp"
		mv "$tmp" "$f"
		printf '+ %s\n' "$f"
	done
done
