#!/usr/bin/env python3
"""
mkfont.py -- one-shot tool that extracts a printable-ASCII subset
from a PSF v1 console font and emits the C source for an embedded
glyph table.

Console fonts on Debian/console-setup-linux are documented as
"public domain by nature" (see /usr/share/doc/console-setup-linux/
copyright), so we can ship the bytes directly.

Usage:

    zcat /usr/share/consolefonts/Lat15-VGA16.psf.gz > tmp/font.psf
    ./tools/mkfont.py tmp/font.psf > src/greeter/font.c
"""

import sys


def main():
    if len(sys.argv) != 2:
        print("usage: mkfont.py <font.psf>", file=sys.stderr)
        sys.exit(1)
    data = open(sys.argv[1], "rb").read()
    if data[0] != 0x36 or data[1] != 0x04:
        print("not a PSF v1 file", file=sys.stderr)
        sys.exit(1)
    mode = data[2]
    rows = data[3]
    nchars = 512 if (mode & 1) else 256
    if rows not in (8, 14, 16):
        print(f"unexpected row count: {rows}", file=sys.stderr)
        sys.exit(1)
    if 4 + nchars * rows > len(data):
        print("truncated PSF", file=sys.stderr)
        sys.exit(1)

    print("/*")
    print(" * font.c -- 8x{} bitmap font, extracted from a PSF v1 file.".format(rows))
    print(" *")
    print(" * Source font is the Linux console Lat15-VGA16 face, which the")
    print(" * console-setup-linux upstream documents as public domain.")
    print(" * Generated by tools/mkfont.py.  Do not edit by hand.")
    print(" */")
    print()
    print('#include "font.h"')
    print()
    print(f"const uint8_t rdp_font_data[RDP_FONT_NUM_GLYPHS][{rows}] = {{")
    for code in range(0x20, 0x7F):
        glyph = data[4 + code * rows : 4 + (code + 1) * rows]
        bytes_str = ", ".join(f"0x{b:02x}" for b in glyph)
        ch = chr(code) if 0x20 <= code < 0x7F else "?"
        print(f"\t[0x{code - 0x20:02x}] = {{ {bytes_str} }},  /* {ch} */")
    print("};")


if __name__ == "__main__":
    main()
