/*
 * Copyright (c) 2026 Renaud Allard <renaud@allard.it>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES.
 */
/*
 * compat.h -- portability shims.
 *
 * Pulls in config.h (generated by ./configure) and then declares
 * prototypes for any libc-ish functions we polyfill in src/common/
 * when the host lacks them.  Including this header gives every
 * translation unit the same view of the host's capabilities.
 */

#ifndef RDP_COMPAT_H
#define RDP_COMPAT_H

#include "config.h"

#include <sys/types.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <unistd.h>

/* OpenBSD safety extensions: define stubs when absent so call sites
 * stay uncluttered.  pledge/unveil return 0 on systems without them. */
#if !HAVE_PLEDGE
static inline int rdp_pledge(const char *p, const char *e)
	{ (void)p; (void)e; return 0; }
#define pledge(p, e) rdp_pledge((p), (e))
#endif

#if !HAVE_UNVEIL
static inline int rdp_unveil(const char *path, const char *perms)
	{ (void)path; (void)perms; return 0; }
#define unveil(p, m) rdp_unveil((p), (m))
#endif

#if !HAVE_STRLCPY
size_t strlcpy(char *dst, const char *src, size_t dsize);
size_t strlcat(char *dst, const char *src, size_t dsize);
#endif

#if !HAVE_REALLOCARRAY
void *reallocarray(void *optr, size_t nmemb, size_t size);
#endif

#if !HAVE_EXPLICIT_BZERO
void explicit_bzero(void *buf, size_t len);
#endif

/* arc4random shim atop getrandom(2) when the host lacks the BSD API. */
#if !HAVE_ARC4RANDOM
uint32_t arc4random(void);
uint32_t arc4random_uniform(uint32_t upper_bound);
void     arc4random_buf(void *buf, size_t len);
#endif

#endif /* RDP_COMPAT_H */
